spring:
  application:
    name: jafka
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: https://jafka.eu.auth0.com/api/v2/
          issuer-uri: http://localhost:8080/auth/realms/jafka