// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package dk.raijin.jafka.protos;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.raijin.jafka.protos.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idempotencyKey = 1;</code>
     * @return The idempotencyKey.
     */
    java.lang.String getIdempotencyKey();
    /**
     * <code>string idempotencyKey = 1;</code>
     * @return The bytes for idempotencyKey.
     */
    com.google.protobuf.ByteString
        getIdempotencyKeyBytes();

    /**
     * <code>string path = 2;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <code>string path = 2;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>string method = 3;</code>
     * @return The method.
     */
    java.lang.String getMethod();
    /**
     * <code>string method = 3;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */
    int getQueryParamsCount();
    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */
    boolean containsQueryParams(
        java.lang.String key);
    /**
     * Use {@link #getQueryParamsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getQueryParams();
    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getQueryParamsMap();
    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */

    java.lang.String getQueryParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */

    java.lang.String getQueryParamsOrThrow(
        java.lang.String key);

    /**
     * <code>string authToken = 5;</code>
     * @return The authToken.
     */
    java.lang.String getAuthToken();
    /**
     * <code>string authToken = 5;</code>
     * @return The bytes for authToken.
     */
    com.google.protobuf.ByteString
        getAuthTokenBytes();

    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */
    int getHeadersCount();
    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */
    boolean containsHeaders(
        java.lang.String key);
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getHeaders();
    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getHeadersMap();
    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */

    java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */

    java.lang.String getHeadersOrThrow(
        java.lang.String key);

    /**
     * <code>string clientIp = 7;</code>
     * @return The clientIp.
     */
    java.lang.String getClientIp();
    /**
     * <code>string clientIp = 7;</code>
     * @return The bytes for clientIp.
     */
    com.google.protobuf.ByteString
        getClientIpBytes();

    /**
     * <code>string userId = 8;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 8;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>repeated string userRoles = 9;</code>
     * @return A list containing the userRoles.
     */
    java.util.List<java.lang.String>
        getUserRolesList();
    /**
     * <code>repeated string userRoles = 9;</code>
     * @return The count of userRoles.
     */
    int getUserRolesCount();
    /**
     * <code>repeated string userRoles = 9;</code>
     * @param index The index of the element to return.
     * @return The userRoles at the given index.
     */
    java.lang.String getUserRoles(int index);
    /**
     * <code>repeated string userRoles = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the userRoles at the given index.
     */
    com.google.protobuf.ByteString
        getUserRolesBytes(int index);

    /**
     * <code>string userAgent = 10;</code>
     * @return The userAgent.
     */
    java.lang.String getUserAgent();
    /**
     * <code>string userAgent = 10;</code>
     * @return The bytes for userAgent.
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    /**
     * <code>string referer = 11;</code>
     * @return The referer.
     */
    java.lang.String getReferer();
    /**
     * <code>string referer = 11;</code>
     * @return The bytes for referer.
     */
    com.google.protobuf.ByteString
        getRefererBytes();

    /**
     * <code>int64 requestSize = 12;</code>
     * @return The requestSize.
     */
    long getRequestSize();

    /**
     * <code>int64 timestamp = 13;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * <pre>
   *This could fit into a remote repository so the schema is shared.
   *Also gives an advantage of having a single source of truth.
   * </pre>
   *
   * Protobuf type {@code dk.raijin.jafka.protos.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.raijin.jafka.protos.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      idempotencyKey_ = "";
      path_ = "";
      method_ = "";
      authToken_ = "";
      clientIp_ = "";
      userId_ = "";
      userRoles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      userAgent_ = "";
      referer_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idempotencyKey_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                queryParams_ = com.google.protobuf.MapField.newMapField(
                    QueryParamsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              queryParams__ = input.readMessage(
                  QueryParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              queryParams_.getMutableMap().put(
                  queryParams__.getKey(), queryParams__.getValue());
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              authToken_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                headers_ = com.google.protobuf.MapField.newMapField(
                    HeadersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              headers__ = input.readMessage(
                  HeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              headers_.getMutableMap().put(
                  headers__.getKey(), headers__.getValue());
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              clientIp_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                userRoles_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              userRoles_.add(s);
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              userAgent_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              referer_ = s;
              break;
            }
            case 96: {

              requestSize_ = input.readInt64();
              break;
            }
            case 104: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          userRoles_ = userRoles_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.raijin.jafka.protos.RequestProto.internal_static_dk_raijin_jafka_protos_Request_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetQueryParams();
        case 6:
          return internalGetHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.raijin.jafka.protos.RequestProto.internal_static_dk_raijin_jafka_protos_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.raijin.jafka.protos.RequestProto.Request.class, dk.raijin.jafka.protos.RequestProto.Request.Builder.class);
    }

    public static final int IDEMPOTENCYKEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object idempotencyKey_;
    /**
     * <code>string idempotencyKey = 1;</code>
     * @return The idempotencyKey.
     */
    @java.lang.Override
    public java.lang.String getIdempotencyKey() {
      java.lang.Object ref = idempotencyKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idempotencyKey_ = s;
        return s;
      }
    }
    /**
     * <code>string idempotencyKey = 1;</code>
     * @return The bytes for idempotencyKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdempotencyKeyBytes() {
      java.lang.Object ref = idempotencyKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idempotencyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object path_;
    /**
     * <code>string path = 2;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <code>string path = 2;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 3;
    private volatile java.lang.Object method_;
    /**
     * <code>string method = 3;</code>
     * @return The method.
     */
    @java.lang.Override
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 3;</code>
     * @return The bytes for method.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUERYPARAMS_FIELD_NUMBER = 4;
    private static final class QueryParamsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  dk.raijin.jafka.protos.RequestProto.internal_static_dk_raijin_jafka_protos_Request_QueryParamsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> queryParams_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetQueryParams() {
      if (queryParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            QueryParamsDefaultEntryHolder.defaultEntry);
      }
      return queryParams_;
    }

    public int getQueryParamsCount() {
      return internalGetQueryParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */

    @java.lang.Override
    public boolean containsQueryParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetQueryParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getQueryParamsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getQueryParams() {
      return getQueryParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getQueryParamsMap() {
      return internalGetQueryParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getQueryParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetQueryParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; queryParams = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getQueryParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetQueryParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int AUTHTOKEN_FIELD_NUMBER = 5;
    private volatile java.lang.Object authToken_;
    /**
     * <code>string authToken = 5;</code>
     * @return The authToken.
     */
    @java.lang.Override
    public java.lang.String getAuthToken() {
      java.lang.Object ref = authToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authToken_ = s;
        return s;
      }
    }
    /**
     * <code>string authToken = 5;</code>
     * @return The bytes for authToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthTokenBytes() {
      java.lang.Object ref = authToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADERS_FIELD_NUMBER = 6;
    private static final class HeadersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  dk.raijin.jafka.protos.RequestProto.internal_static_dk_raijin_jafka_protos_Request_HeadersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> headers_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetHeaders() {
      if (headers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeadersDefaultEntryHolder.defaultEntry);
      }
      return headers_;
    }

    public int getHeadersCount() {
      return internalGetHeaders().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */

    @java.lang.Override
    public boolean containsHeaders(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetHeaders().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
      return getHeadersMap();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
      return internalGetHeaders().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; headers = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getHeadersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int CLIENTIP_FIELD_NUMBER = 7;
    private volatile java.lang.Object clientIp_;
    /**
     * <code>string clientIp = 7;</code>
     * @return The clientIp.
     */
    @java.lang.Override
    public java.lang.String getClientIp() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIp_ = s;
        return s;
      }
    }
    /**
     * <code>string clientIp = 7;</code>
     * @return The bytes for clientIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIpBytes() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 8;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 8;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 8;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERROLES_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList userRoles_;
    /**
     * <code>repeated string userRoles = 9;</code>
     * @return A list containing the userRoles.
     */
    public com.google.protobuf.ProtocolStringList
        getUserRolesList() {
      return userRoles_;
    }
    /**
     * <code>repeated string userRoles = 9;</code>
     * @return The count of userRoles.
     */
    public int getUserRolesCount() {
      return userRoles_.size();
    }
    /**
     * <code>repeated string userRoles = 9;</code>
     * @param index The index of the element to return.
     * @return The userRoles at the given index.
     */
    public java.lang.String getUserRoles(int index) {
      return userRoles_.get(index);
    }
    /**
     * <code>repeated string userRoles = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the userRoles at the given index.
     */
    public com.google.protobuf.ByteString
        getUserRolesBytes(int index) {
      return userRoles_.getByteString(index);
    }

    public static final int USERAGENT_FIELD_NUMBER = 10;
    private volatile java.lang.Object userAgent_;
    /**
     * <code>string userAgent = 10;</code>
     * @return The userAgent.
     */
    @java.lang.Override
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      }
    }
    /**
     * <code>string userAgent = 10;</code>
     * @return The bytes for userAgent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERER_FIELD_NUMBER = 11;
    private volatile java.lang.Object referer_;
    /**
     * <code>string referer = 11;</code>
     * @return The referer.
     */
    @java.lang.Override
    public java.lang.String getReferer() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referer_ = s;
        return s;
      }
    }
    /**
     * <code>string referer = 11;</code>
     * @return The bytes for referer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRefererBytes() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTSIZE_FIELD_NUMBER = 12;
    private long requestSize_;
    /**
     * <code>int64 requestSize = 12;</code>
     * @return The requestSize.
     */
    @java.lang.Override
    public long getRequestSize() {
      return requestSize_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 13;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 13;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdempotencyKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idempotencyKey_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, path_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, method_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetQueryParams(),
          QueryParamsDefaultEntryHolder.defaultEntry,
          4);
      if (!getAuthTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, authToken_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetHeaders(),
          HeadersDefaultEntryHolder.defaultEntry,
          6);
      if (!getClientIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, clientIp_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userId_);
      }
      for (int i = 0; i < userRoles_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, userRoles_.getRaw(i));
      }
      if (!getUserAgentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, userAgent_);
      }
      if (!getRefererBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, referer_);
      }
      if (requestSize_ != 0L) {
        output.writeInt64(12, requestSize_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(13, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdempotencyKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idempotencyKey_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, path_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, method_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetQueryParams().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        queryParams__ = QueryParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, queryParams__);
      }
      if (!getAuthTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, authToken_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetHeaders().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        headers__ = HeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, headers__);
      }
      if (!getClientIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, clientIp_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < userRoles_.size(); i++) {
          dataSize += computeStringSizeNoTag(userRoles_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUserRolesList().size();
      }
      if (!getUserAgentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, userAgent_);
      }
      if (!getRefererBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, referer_);
      }
      if (requestSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, requestSize_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.raijin.jafka.protos.RequestProto.Request)) {
        return super.equals(obj);
      }
      dk.raijin.jafka.protos.RequestProto.Request other = (dk.raijin.jafka.protos.RequestProto.Request) obj;

      if (!getIdempotencyKey()
          .equals(other.getIdempotencyKey())) return false;
      if (!getPath()
          .equals(other.getPath())) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (!internalGetQueryParams().equals(
          other.internalGetQueryParams())) return false;
      if (!getAuthToken()
          .equals(other.getAuthToken())) return false;
      if (!internalGetHeaders().equals(
          other.internalGetHeaders())) return false;
      if (!getClientIp()
          .equals(other.getClientIp())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getUserRolesList()
          .equals(other.getUserRolesList())) return false;
      if (!getUserAgent()
          .equals(other.getUserAgent())) return false;
      if (!getReferer()
          .equals(other.getReferer())) return false;
      if (getRequestSize()
          != other.getRequestSize()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDEMPOTENCYKEY_FIELD_NUMBER;
      hash = (53 * hash) + getIdempotencyKey().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      if (!internalGetQueryParams().getMap().isEmpty()) {
        hash = (37 * hash) + QUERYPARAMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetQueryParams().hashCode();
      }
      hash = (37 * hash) + AUTHTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAuthToken().hashCode();
      if (!internalGetHeaders().getMap().isEmpty()) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetHeaders().hashCode();
      }
      hash = (37 * hash) + CLIENTIP_FIELD_NUMBER;
      hash = (53 * hash) + getClientIp().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      if (getUserRolesCount() > 0) {
        hash = (37 * hash) + USERROLES_FIELD_NUMBER;
        hash = (53 * hash) + getUserRolesList().hashCode();
      }
      hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
      hash = (53 * hash) + getUserAgent().hashCode();
      hash = (37 * hash) + REFERER_FIELD_NUMBER;
      hash = (53 * hash) + getReferer().hashCode();
      hash = (37 * hash) + REQUESTSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestSize());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.raijin.jafka.protos.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.raijin.jafka.protos.RequestProto.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *This could fit into a remote repository so the schema is shared.
     *Also gives an advantage of having a single source of truth.
     * </pre>
     *
     * Protobuf type {@code dk.raijin.jafka.protos.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.raijin.jafka.protos.Request)
        dk.raijin.jafka.protos.RequestProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.raijin.jafka.protos.RequestProto.internal_static_dk_raijin_jafka_protos_Request_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetQueryParams();
          case 6:
            return internalGetHeaders();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableQueryParams();
          case 6:
            return internalGetMutableHeaders();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.raijin.jafka.protos.RequestProto.internal_static_dk_raijin_jafka_protos_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.raijin.jafka.protos.RequestProto.Request.class, dk.raijin.jafka.protos.RequestProto.Request.Builder.class);
      }

      // Construct using dk.raijin.jafka.protos.RequestProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idempotencyKey_ = "";

        path_ = "";

        method_ = "";

        internalGetMutableQueryParams().clear();
        authToken_ = "";

        internalGetMutableHeaders().clear();
        clientIp_ = "";

        userId_ = "";

        userRoles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        userAgent_ = "";

        referer_ = "";

        requestSize_ = 0L;

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.raijin.jafka.protos.RequestProto.internal_static_dk_raijin_jafka_protos_Request_descriptor;
      }

      @java.lang.Override
      public dk.raijin.jafka.protos.RequestProto.Request getDefaultInstanceForType() {
        return dk.raijin.jafka.protos.RequestProto.Request.getDefaultInstance();
      }

      @java.lang.Override
      public dk.raijin.jafka.protos.RequestProto.Request build() {
        dk.raijin.jafka.protos.RequestProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.raijin.jafka.protos.RequestProto.Request buildPartial() {
        dk.raijin.jafka.protos.RequestProto.Request result = new dk.raijin.jafka.protos.RequestProto.Request(this);
        int from_bitField0_ = bitField0_;
        result.idempotencyKey_ = idempotencyKey_;
        result.path_ = path_;
        result.method_ = method_;
        result.queryParams_ = internalGetQueryParams();
        result.queryParams_.makeImmutable();
        result.authToken_ = authToken_;
        result.headers_ = internalGetHeaders();
        result.headers_.makeImmutable();
        result.clientIp_ = clientIp_;
        result.userId_ = userId_;
        if (((bitField0_ & 0x00000004) != 0)) {
          userRoles_ = userRoles_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.userRoles_ = userRoles_;
        result.userAgent_ = userAgent_;
        result.referer_ = referer_;
        result.requestSize_ = requestSize_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.raijin.jafka.protos.RequestProto.Request) {
          return mergeFrom((dk.raijin.jafka.protos.RequestProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.raijin.jafka.protos.RequestProto.Request other) {
        if (other == dk.raijin.jafka.protos.RequestProto.Request.getDefaultInstance()) return this;
        if (!other.getIdempotencyKey().isEmpty()) {
          idempotencyKey_ = other.idempotencyKey_;
          onChanged();
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        internalGetMutableQueryParams().mergeFrom(
            other.internalGetQueryParams());
        if (!other.getAuthToken().isEmpty()) {
          authToken_ = other.authToken_;
          onChanged();
        }
        internalGetMutableHeaders().mergeFrom(
            other.internalGetHeaders());
        if (!other.getClientIp().isEmpty()) {
          clientIp_ = other.clientIp_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.userRoles_.isEmpty()) {
          if (userRoles_.isEmpty()) {
            userRoles_ = other.userRoles_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUserRolesIsMutable();
            userRoles_.addAll(other.userRoles_);
          }
          onChanged();
        }
        if (!other.getUserAgent().isEmpty()) {
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (!other.getReferer().isEmpty()) {
          referer_ = other.referer_;
          onChanged();
        }
        if (other.getRequestSize() != 0L) {
          setRequestSize(other.getRequestSize());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.raijin.jafka.protos.RequestProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.raijin.jafka.protos.RequestProto.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object idempotencyKey_ = "";
      /**
       * <code>string idempotencyKey = 1;</code>
       * @return The idempotencyKey.
       */
      public java.lang.String getIdempotencyKey() {
        java.lang.Object ref = idempotencyKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idempotencyKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idempotencyKey = 1;</code>
       * @return The bytes for idempotencyKey.
       */
      public com.google.protobuf.ByteString
          getIdempotencyKeyBytes() {
        java.lang.Object ref = idempotencyKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idempotencyKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idempotencyKey = 1;</code>
       * @param value The idempotencyKey to set.
       * @return This builder for chaining.
       */
      public Builder setIdempotencyKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idempotencyKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idempotencyKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdempotencyKey() {
        
        idempotencyKey_ = getDefaultInstance().getIdempotencyKey();
        onChanged();
        return this;
      }
      /**
       * <code>string idempotencyKey = 1;</code>
       * @param value The bytes for idempotencyKey to set.
       * @return This builder for chaining.
       */
      public Builder setIdempotencyKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idempotencyKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>string path = 2;</code>
       * @return The path.
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string path = 2;</code>
       * @return The bytes for path.
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string path = 2;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string path = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>string path = 2;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>string method = 3;</code>
       * @return The method.
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method = 3;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 3;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 3;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> queryParams_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetQueryParams() {
        if (queryParams_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              QueryParamsDefaultEntryHolder.defaultEntry);
        }
        return queryParams_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableQueryParams() {
        onChanged();;
        if (queryParams_ == null) {
          queryParams_ = com.google.protobuf.MapField.newMapField(
              QueryParamsDefaultEntryHolder.defaultEntry);
        }
        if (!queryParams_.isMutable()) {
          queryParams_ = queryParams_.copy();
        }
        return queryParams_;
      }

      public int getQueryParamsCount() {
        return internalGetQueryParams().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; queryParams = 4;</code>
       */

      @java.lang.Override
      public boolean containsQueryParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetQueryParams().getMap().containsKey(key);
      }
      /**
       * Use {@link #getQueryParamsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getQueryParams() {
        return getQueryParamsMap();
      }
      /**
       * <code>map&lt;string, string&gt; queryParams = 4;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getQueryParamsMap() {
        return internalGetQueryParams().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; queryParams = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getQueryParamsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetQueryParams().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; queryParams = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getQueryParamsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetQueryParams().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearQueryParams() {
        internalGetMutableQueryParams().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; queryParams = 4;</code>
       */

      public Builder removeQueryParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableQueryParams().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableQueryParams() {
        return internalGetMutableQueryParams().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; queryParams = 4;</code>
       */
      public Builder putQueryParams(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableQueryParams().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; queryParams = 4;</code>
       */

      public Builder putAllQueryParams(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableQueryParams().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object authToken_ = "";
      /**
       * <code>string authToken = 5;</code>
       * @return The authToken.
       */
      public java.lang.String getAuthToken() {
        java.lang.Object ref = authToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authToken = 5;</code>
       * @return The bytes for authToken.
       */
      public com.google.protobuf.ByteString
          getAuthTokenBytes() {
        java.lang.Object ref = authToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authToken = 5;</code>
       * @param value The authToken to set.
       * @return This builder for chaining.
       */
      public Builder setAuthToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authToken = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthToken() {
        
        authToken_ = getDefaultInstance().getAuthToken();
        onChanged();
        return this;
      }
      /**
       * <code>string authToken = 5;</code>
       * @param value The bytes for authToken to set.
       * @return This builder for chaining.
       */
      public Builder setAuthTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authToken_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> headers_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetHeaders() {
        if (headers_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              HeadersDefaultEntryHolder.defaultEntry);
        }
        return headers_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableHeaders() {
        onChanged();;
        if (headers_ == null) {
          headers_ = com.google.protobuf.MapField.newMapField(
              HeadersDefaultEntryHolder.defaultEntry);
        }
        if (!headers_.isMutable()) {
          headers_ = headers_.copy();
        }
        return headers_;
      }

      public int getHeadersCount() {
        return internalGetHeaders().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 6;</code>
       */

      @java.lang.Override
      public boolean containsHeaders(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetHeaders().getMap().containsKey(key);
      }
      /**
       * Use {@link #getHeadersMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
        return getHeadersMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 6;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
        return internalGetHeaders().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 6;</code>
       */
      @java.lang.Override

      public java.lang.String getHeadersOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetHeaders().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 6;</code>
       */
      @java.lang.Override

      public java.lang.String getHeadersOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetHeaders().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearHeaders() {
        internalGetMutableHeaders().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 6;</code>
       */

      public Builder removeHeaders(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableHeaders().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableHeaders() {
        return internalGetMutableHeaders().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 6;</code>
       */
      public Builder putHeaders(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableHeaders().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 6;</code>
       */

      public Builder putAllHeaders(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableHeaders().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object clientIp_ = "";
      /**
       * <code>string clientIp = 7;</code>
       * @return The clientIp.
       */
      public java.lang.String getClientIp() {
        java.lang.Object ref = clientIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientIp = 7;</code>
       * @return The bytes for clientIp.
       */
      public com.google.protobuf.ByteString
          getClientIpBytes() {
        java.lang.Object ref = clientIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientIp = 7;</code>
       * @param value The clientIp to set.
       * @return This builder for chaining.
       */
      public Builder setClientIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientIp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientIp() {
        
        clientIp_ = getDefaultInstance().getClientIp();
        onChanged();
        return this;
      }
      /**
       * <code>string clientIp = 7;</code>
       * @param value The bytes for clientIp to set.
       * @return This builder for chaining.
       */
      public Builder setClientIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 8;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 8;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 8;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 8;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList userRoles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUserRolesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          userRoles_ = new com.google.protobuf.LazyStringArrayList(userRoles_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @return A list containing the userRoles.
       */
      public com.google.protobuf.ProtocolStringList
          getUserRolesList() {
        return userRoles_.getUnmodifiableView();
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @return The count of userRoles.
       */
      public int getUserRolesCount() {
        return userRoles_.size();
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @param index The index of the element to return.
       * @return The userRoles at the given index.
       */
      public java.lang.String getUserRoles(int index) {
        return userRoles_.get(index);
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @param index The index of the value to return.
       * @return The bytes of the userRoles at the given index.
       */
      public com.google.protobuf.ByteString
          getUserRolesBytes(int index) {
        return userRoles_.getByteString(index);
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @param index The index to set the value at.
       * @param value The userRoles to set.
       * @return This builder for chaining.
       */
      public Builder setUserRoles(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserRolesIsMutable();
        userRoles_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @param value The userRoles to add.
       * @return This builder for chaining.
       */
      public Builder addUserRoles(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserRolesIsMutable();
        userRoles_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @param values The userRoles to add.
       * @return This builder for chaining.
       */
      public Builder addAllUserRoles(
          java.lang.Iterable<java.lang.String> values) {
        ensureUserRolesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userRoles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserRoles() {
        userRoles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userRoles = 9;</code>
       * @param value The bytes of the userRoles to add.
       * @return This builder for chaining.
       */
      public Builder addUserRolesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureUserRolesIsMutable();
        userRoles_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object userAgent_ = "";
      /**
       * <code>string userAgent = 10;</code>
       * @return The userAgent.
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userAgent = 10;</code>
       * @return The bytes for userAgent.
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userAgent = 10;</code>
       * @param value The userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userAgent = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserAgent() {
        
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>string userAgent = 10;</code>
       * @param value The bytes for userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userAgent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object referer_ = "";
      /**
       * <code>string referer = 11;</code>
       * @return The referer.
       */
      public java.lang.String getReferer() {
        java.lang.Object ref = referer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          referer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string referer = 11;</code>
       * @return The bytes for referer.
       */
      public com.google.protobuf.ByteString
          getRefererBytes() {
        java.lang.Object ref = referer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string referer = 11;</code>
       * @param value The referer to set.
       * @return This builder for chaining.
       */
      public Builder setReferer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        referer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string referer = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearReferer() {
        
        referer_ = getDefaultInstance().getReferer();
        onChanged();
        return this;
      }
      /**
       * <code>string referer = 11;</code>
       * @param value The bytes for referer to set.
       * @return This builder for chaining.
       */
      public Builder setRefererBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        referer_ = value;
        onChanged();
        return this;
      }

      private long requestSize_ ;
      /**
       * <code>int64 requestSize = 12;</code>
       * @return The requestSize.
       */
      @java.lang.Override
      public long getRequestSize() {
        return requestSize_;
      }
      /**
       * <code>int64 requestSize = 12;</code>
       * @param value The requestSize to set.
       * @return This builder for chaining.
       */
      public Builder setRequestSize(long value) {
        
        requestSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestSize = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestSize() {
        
        requestSize_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 13;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 13;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.raijin.jafka.protos.Request)
    }

    // @@protoc_insertion_point(class_scope:dk.raijin.jafka.protos.Request)
    private static final dk.raijin.jafka.protos.RequestProto.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.raijin.jafka.protos.RequestProto.Request();
    }

    public static dk.raijin.jafka.protos.RequestProto.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.raijin.jafka.protos.RequestProto.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_raijin_jafka_protos_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_raijin_jafka_protos_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_raijin_jafka_protos_Request_QueryParamsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_raijin_jafka_protos_Request_QueryParamsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_raijin_jafka_protos_Request_HeadersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_raijin_jafka_protos_Request_HeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\026dk.raijin.jafka.protos\"" +
      "\275\003\n\007Request\022\026\n\016idempotencyKey\030\001 \001(\t\022\014\n\004p" +
      "ath\030\002 \001(\t\022\016\n\006method\030\003 \001(\t\022E\n\013queryParams" +
      "\030\004 \003(\01320.dk.raijin.jafka.protos.Request." +
      "QueryParamsEntry\022\021\n\tauthToken\030\005 \001(\t\022=\n\007h" +
      "eaders\030\006 \003(\0132,.dk.raijin.jafka.protos.Re" +
      "quest.HeadersEntry\022\020\n\010clientIp\030\007 \001(\t\022\016\n\006" +
      "userId\030\010 \001(\t\022\021\n\tuserRoles\030\t \003(\t\022\021\n\tuserA" +
      "gent\030\n \001(\t\022\017\n\007referer\030\013 \001(\t\022\023\n\013requestSi" +
      "ze\030\014 \001(\003\022\021\n\ttimestamp\030\r \001(\003\0322\n\020QueryPara" +
      "msEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032" +
      ".\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001B&\n\026dk.raijin.jafka.protosB\014Reque" +
      "stProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dk_raijin_jafka_protos_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dk_raijin_jafka_protos_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_raijin_jafka_protos_Request_descriptor,
        new java.lang.String[] { "IdempotencyKey", "Path", "Method", "QueryParams", "AuthToken", "Headers", "ClientIp", "UserId", "UserRoles", "UserAgent", "Referer", "RequestSize", "Timestamp", });
    internal_static_dk_raijin_jafka_protos_Request_QueryParamsEntry_descriptor =
      internal_static_dk_raijin_jafka_protos_Request_descriptor.getNestedTypes().get(0);
    internal_static_dk_raijin_jafka_protos_Request_QueryParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_raijin_jafka_protos_Request_QueryParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_dk_raijin_jafka_protos_Request_HeadersEntry_descriptor =
      internal_static_dk_raijin_jafka_protos_Request_descriptor.getNestedTypes().get(1);
    internal_static_dk_raijin_jafka_protos_Request_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_raijin_jafka_protos_Request_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
